name: ubuntu_latest

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu_Latest",
            os: ubuntu-latest
          }

    steps:
      - name: Checkout Repository and Submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: ls
        run: ls ${{runner.workspace}}

      - name: cd
        run: ls ${{runner.workspace}}

      - name: ls 2
        run: ls
