name: ubuntu_latest

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu_Latest",
            os: ubuntu-latest
          }

    steps:
      - name: Checkout Repository and Submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Move module into root
        run: mv py_instrument_control_lib/* .

      - name: Delete unneeded files
        run: rm -r pyproject.toml specifications py_instrument_control_lib

      - name: ls
        run: ls

      - name: Add changes
        run: git add .

      - name: Commit changes
        run: git commit -m "Move module into root directory"

      - name: Push changes
        run: git push --force origin main:package_submodule
